### ISSUE TITLE
Small wiki change

### ISSUE THREAD

**Issue by civanescu** [arxenix/starborne-assistant#14]
Should be updated with list of games is:
GET https://sba.starborne.com/api/Player/GetGames

**Comment by arxenix** [comment]
done, thanks!

**Comment by civanescu** [comment]
I don't know where I can ask stupid question.... I'm trying to connect with python to the hubspot and I don't know what token should I use.... the "Bearer <token>" from OAuth, or the PlayerJoinToken I've received? 

I keep receiving this error:

`Negotiate url:https://cluster1.starborne.com/beta01/GameHub/negotiate`
`Response status code502`
`AuthHubConnection`
`502`

**Comment by civanescu** [comment]
Solved :), I was trying to log on a server where I didn't have account...
